language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2

matrix:
  allow_failures:
    - php: 7.0

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email: false
